= Interscript.js

== Purpose

The Interscript transliteration/transcription framework in JavaScript.
Supports all Interscript maps.

== Usage

Install
~~~~~~~~
* Download
https://github.com/interscript/interscript-js/blob/master/interscript.js[Interscript.js ^]
file directly
* Or in the terminal, you can clone the repository.
+
[source,shell]
----------------
# git clone https://github.com/interscript/interscript-js.git
# cd ./interscript-js
----------------

How To Use
~~~~~~~~~~
* Add a script tag in your html
+
[source,html]
-----------------
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="path/to/interscript.js"></script>
  </head>
  <body>
  </body>
  <script>
  Opal.Interscript.$on_load().then(function() {
      // here use interscript.js
  });
  </script>
</html>
-----------------

* List out the supported systems
+
[source,javascript]
-----------------
<script>
    Opal.Interscript.$on_load().then(function() {
        Object.keys(InterscriptMaps).forEach(system => {
            document.write(`<option value="${system}" selected>${system}</option>`);
        })
    });
</script>
-----------------
Here, *InterscriptMaps* is a global variable defined in the interscript.js file, it has the supported systems as json format. You can access this object from anywhere you want.

* Get a rule from a system
+
[source,javascript]
-----------------
<script>
    Opal.Interscript.$on_load().then(function() {
        var system = 'bgnpcgn-rus-Cyrl-Latn-1947';
        const system_code = sel.options[sel.selectedIndex].text;
        var httpRequest = new XMLHttpRequest();
        httpRequest.onreadystatechange = function() {
          if (httpRequest.readyState === XMLHttpRequest.DONE) {
            Opal.Interscript.$load_map_json(system_code, httpRequest.responseText);

            var data = JSON.parse(InterscriptMaps[system]);
            data.map.rules.forEach(function(rule){
              // write your code here to handle rule
            });
          }
        };
        httpRequest.open('GET', "maps/"+system_code+".json", true);
        httpRequest.send();
    });
</script>
-----------------

* How to use a system for transliteration
+
[source,javascript]
-----------------
<script>
    Opal.Interscript.$on_load().then(function() {
        var system = 'bgnpcgn-rus-Cyrl-Latn-1947';
        var sample = 'Эх, тройка! птица тройка, кто тебя выдумал? знать, у бойкого народа ты могла только родиться, в той земле, что не любит шутить, а ровнем-гладнем разметнулась на полсвета, да и ступай считать версты, пока не зарябит тебе в очи. И не хитрый, кажись, дорожный снаряд, не железным схвачен винтом, а наскоро живьём с одним топором да долотом снарядил и собрал тебя ярославский расторопный мужик. Не в немецких ботфортах ямщик: борода да рукавицы, и сидит чёрт знает на чём; а привстал, да замахнулся, да затянул песню — кони вихрем, спицы в колесах смешались в один гладкий круг, только дрогнула дорога, да вскрикнул в испуге остановившийся пешеход — и вон она понеслась, понеслась, понеслась! Н.В. Гоголь';
        var httpRequest = new XMLHttpRequest();
        httpRequest.onreadystatechange = function() {
          if (httpRequest.readyState === XMLHttpRequest.DONE) {
            Opal.Interscript.$load_map_json(system, httpRequest.responseText);

            var result = Opal.Interscript.$transliterate(system, sample);
            console.log(result);
          }
        };
        httpRequest.open('GET', "maps/"+system+".json", true);
        httpRequest.send();
    });
</script>
-----------------

=== Usage from Node

NOTE: Interscript is not bundled as a well-behaved module yet; requiring it defines a global `Opal` identifier.

Install:

[source,sh]
--
yarn add interscript
--

Use:

[source,javascript]
--
require('interscript');

const system = 'bgnpcgn-rus-Cyrl-Latn-1947';
const text = 'Эх, тройка! птица тройка, кто тебя выдумал? знать, у бойкого народа ты могла только родиться, в той земле, что не любит шутить, а ровнем-гладнем разметнулась на полсвета, да и ступай считать версты, пока не зарябит тебе в очи. И не хитрый, кажись, дорожный снаряд, не железным схвачен винтом, а наскоро живьём с одним топором да долотом снарядил и собрал тебя ярославский расторопный мужик. Не в немецких ботфортах ямщик: борода да рукавицы, и сидит чёрт знает на чём; а привстал, да замахнулся, да затянул песню — кони вихрем, спицы в колесах смешались в один гладкий круг, только дрогнула дорога, да вскрикнул в испуге остановившийся пешеход — и вон она понеслась, понеслась, понеслась! Н.В. Гоголь';
const json = require('interscript/maps')[system];
Opal.Interscript.$load_map_json(system, json);
const result = Opal.Interscript.$transliterate(system, text);
console.log(result);
--

=== Demo
The demo is included in the repository.


== Development

Interscript.js is generated through Opal on the `interscript` gem in Ruby.

=== Release process

Bump version in package.json; commit and tag the repo appropriately; push to Github and call `npm publish`.

TODO: Redo build process, generate JS as build artifact and bundle the code for browser and Node with proper use of exports.
