name: deploy

on:
  push:
    branches: [ master, staging ]

jobs:
  trigger-deploy:
    name: Trigger master deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build event type
        id: event_type
        run: |
          echo "##[set-output name=value;]deploy_${GITHUB_REF##*/}"
      - name: Trigger jsdemo.interscript.com
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.INTERSCRIPT_CI_PAT }}
          repository: interscript/jsdemo.interscript.com
          event-type: ${{ steps.event_type.outputs.value }}