name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v7
        with:
          repository: interscript/interscript

      - name: Bootstrap packages
        run: ruby bootstrap.rb

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: ruby

      - uses: actions/setup-node@v7
        with:
          node-version: '22'
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: js/package-lock.json

      - name: Install gems
        working-directory: ruby
        run: bundle install --jobs 4 --retry 3 --with jsexec --without secryst

      - name: Test Ruby package
        working-directory: ruby
        run: bundle exec rake

      - name: Test JS package
        working-directory: js
        run: npm ci && npm run prepareMaps && npm test

      - name: Publish to npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.INTERSCRIPT_NPM_TOKEN }}
        working-directory: js
        run: |
          npm run prepareMaps
          npm publish --access public
